[package]
name = "vane"
version = "0.6.7"
edition = "2024"
rust-version = "1.92"
[package.metadata.docs.rs]
all-features = true

[[bin]]
name = "vane"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }